# Generated by Django 5.2.17 on 2026-10-03 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0023_rag_baselines"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationLegacyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("actor", models.CharField(max_length=150)),
                ("reason", models.CharField(max_length=1000)),
                ("capture_sha256", models.CharField(max_length=64, unique=True)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("evidence", models.JSONField()),
                ("calls", models.PositiveIntegerField()),
                ("input_tokens", models.PositiveBigIntegerField()),
                ("output_tokens", models.PositiveBigIntegerField()),
                ("before", models.JSONField()),
                ("after", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="evaluations.evaluationbudget",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_usage",
                        to="evaluations.evaluationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("calls__gt", 0)), name="legacy_usage_calls"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("actor", ""), _negated=True),
                            models.Q(("reason", ""), _negated=True),
                        ),
                        name="legacy_usage_attribution",
                    ),
                ],
            },
        ),
    ]
