# Generated by Django 5.2.17 on 2026-10-03 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0024_legacy_usage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evaluationbudgetchange",
            name="budget_change_cli_source",
        ),
        migrations.AddField(
            model_name="evaluationbudgetchange",
            name="authenticated_actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluationbudgetchange",
            name="expected_revision",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="evaluationlegacyusage",
            name="actor_source",
            field=models.CharField(default="CLI", editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name="evaluationlegacyusage",
            name="authenticated_actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationbudgetchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("authenticated_actor__isnull", True),
                        ("expected_revision__isnull", True),
                        ("source", "CLI"),
                    ),
                    models.Q(
                        ("authenticated_actor__isnull", False),
                        ("expected_revision__isnull", False),
                        ("source", "CORE_ADMIN"),
                    ),
                    _connector="OR",
                ),
                name="budget_change_actor_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationlegacyusage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("actor_source", "CLI"), ("authenticated_actor__isnull", True)),
                    models.Q(
                        ("actor_source", "CORE_ADMIN"), ("authenticated_actor__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="legacy_usage_actor_source",
            ),
        ),
    ]
