function classes(...groups: string[]) {
  return groups.join(' ')
}

const focus = 'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-primary'

// 색상이나 CSS 속성이 아니라 관심 공고함에서 맡는 UI 역할을 이름으로 사용합니다.
// 화면 통일안 19~21: 머리글 왼쪽 세그먼트(목록 · 달력 · 진행 관리) → 필터 막대 한 줄 → 적용 조건 칩 → 표(모바일 카드) / 달력 + 다가오는 마감 / 5열 보드.
export const savedCalendarStyles = {
  lede: 'm-0 -mt-2 text-[0.8125rem] leading-[1.6] text-ink-muted',
  // 필터 막대: 왼쪽 검색 알약(최소 12rem, 남는 폭을 차지), 오른쪽 지역·분야·대상 다중 선택 드롭다운. 폭이 모자라면 줄을 바꿉니다.
  filterBar: 'flex flex-wrap items-center gap-2',
  search: classes(
    'flex min-h-10 min-w-[12rem] flex-[1_1_16rem] items-center gap-2 rounded-full border border-line bg-white px-3.5',
    'text-[0.85rem] text-ink-subtle focus-within:border-brand-primary focus-within:shadow-[0_0_0_3px_rgb(8_127_70_/_12%)] max-chat:basis-full',
  ),
  searchInput: 'min-w-0 flex-1 border-0 bg-transparent text-[0.85rem] text-ink outline-0 placeholder:text-ink-muted',
  appliedFilters: 'flex flex-wrap items-center gap-2 text-[0.78rem] text-ink-muted',
  filterChip: classes(
    'inline-flex min-h-8 cursor-pointer items-center gap-1.5 rounded-full border border-line bg-white px-3 text-[0.74rem] font-semibold text-ink',
    'hover:border-brand-primary hover:text-brand-primary', focus,
  ),
  resetFilters: `cursor-pointer border-0 bg-transparent p-0 text-[0.74rem] font-bold text-brand-primary hover:text-brand-hover ${focus}`,
  // 진행 단계 배지 버튼(▾)과 바꾸기 패널.
  stageButton: classes(
    'inline-flex h-7 cursor-pointer items-center gap-1 rounded-full border-0 px-2.5 text-[0.7rem] font-extrabold whitespace-nowrap',
    'hover:brightness-95', focus,
  ),
  panel: classes(
    'fixed inset-y-0 right-0 z-20 flex w-[400px] max-w-full flex-col border-l border-line bg-surface shadow-[-18px_0_40px_rgb(32_33_36_/_12%)]',
    'max-[599px]:inset-x-0 max-[599px]:top-auto max-[599px]:bottom-0 max-[599px]:w-auto max-[599px]:max-h-[86dvh] max-[599px]:rounded-t-[22px] max-[599px]:border-0 max-[599px]:shadow-[0_-12px_32px_rgb(32_33_36_/_12%)]',
  ),
  panelScrim: 'hidden max-[599px]:block max-[599px]:fixed max-[599px]:inset-0 max-[599px]:z-[19] max-[599px]:cursor-default max-[599px]:border-0 max-[599px]:bg-black/35 max-[599px]:p-0',
  panelHeader: 'relative flex shrink-0 items-start justify-between gap-3 border-b border-line px-5 pt-4 pb-3 max-[599px]:pt-5',
  panelGrab: 'hidden max-[599px]:block max-[599px]:absolute max-[599px]:top-2 max-[599px]:left-1/2 max-[599px]:h-1 max-[599px]:w-9 max-[599px]:-translate-x-1/2 max-[599px]:rounded-full max-[599px]:bg-line-strong',
  panelHeading: 'flex min-w-0 flex-col gap-0.5',
  panelTitle: 'm-0 text-[1rem] font-bold text-ink',
  panelSubtitle: 'm-0 truncate text-[0.8125rem] text-ink-muted',
  panelClose: 'grid size-9 shrink-0 cursor-pointer place-items-center rounded-full border-0 bg-transparent text-ink-muted hover:bg-surface-muted hover:text-ink focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-primary',
  panelBody: 'flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto overscroll-contain px-5 py-4',
  panelFooter: 'flex shrink-0 items-center gap-2 border-t border-line px-5 py-3 max-[599px]:pb-[calc(0.75rem+env(safe-area-inset-bottom))]',
  panelGhostButton: 'inline-flex h-11 shrink-0 cursor-pointer items-center justify-center rounded-full border-0 bg-transparent px-4 text-[0.9375rem] font-semibold text-ink-muted hover:bg-surface-muted hover:text-ink focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-primary max-[599px]:flex-1',
  panelPrimaryButton: classes(
    'inline-flex h-11 flex-1 cursor-pointer items-center justify-center rounded-full border-0 bg-brand-primary px-5 text-[0.9375rem] font-semibold text-white no-underline',
    'hover:bg-brand-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-primary disabled:cursor-not-allowed disabled:opacity-50 max-[599px]:flex-[2]',
  ),
  stageList: 'm-0 flex flex-col gap-1 border-0 p-0',
  stageOption: 'flex cursor-pointer items-start gap-3 rounded-xl px-3 py-2.5 hover:bg-surface-muted has-[:checked]:bg-brand-soft [&>input]:mt-1 [&>input]:accent-brand-primary',
  stageOptionText: 'flex min-w-0 flex-col',
  stageOptionLabel: 'text-[0.9rem] font-bold text-ink',
  stageOptionHint: 'text-[0.75rem] text-ink-muted',
  stageNote: 'flex flex-col gap-1 rounded-[0.85rem] border border-info-line bg-info-soft px-4 py-3 text-[0.8125rem] leading-[1.55] text-ink',
  // 목록: PC는 표, 좁은 폭(760px 미만)은 카드입니다.
  table: 'w-full border-separate border-spacing-0 overflow-hidden rounded-[1.4rem] border border-line bg-white text-[0.8125rem]',
  th: 'bg-[#f6f7f8] px-4 py-2.5 text-left text-[0.7rem] font-bold whitespace-nowrap text-ink-muted',
  td: 'border-t border-line px-4 py-3 align-middle text-ink-muted',
  tdTitle: 'min-w-0 text-ink',
  rowMeta: 'mb-1 flex flex-wrap items-center gap-1.5',
  rowTitle: 'block text-[0.9rem] font-bold leading-[1.4] text-ink no-underline hover:text-brand-primary [overflow-wrap:anywhere]',
  rowSub: 'mt-0.5 block text-[0.75rem] text-ink-muted',
  rowDeadline: 'whitespace-nowrap tabular-nums',
  rowDate: 'whitespace-nowrap tabular-nums',
  rowActions: 'flex items-center justify-end gap-2',
  cardList: 'flex flex-col gap-3',
  card: 'flex flex-col gap-2 rounded-[1.2rem] border border-line bg-white p-4',
  cardFoot: 'mt-1 flex items-center gap-2',
  cardSourceLink: 'mr-auto inline-flex items-center gap-1 text-[0.78rem] font-semibold text-ink-muted no-underline hover:text-brand-primary',
  iconButton: classes(
    'grid size-9 shrink-0 cursor-pointer place-items-center rounded-full border border-line bg-white text-brand-primary',
    'hover:border-brand-primary hover:bg-brand-soft disabled:cursor-wait disabled:opacity-50', focus,
  ),
  smallButton: classes(
    'inline-flex min-h-9 shrink-0 cursor-pointer items-center justify-center rounded-full border border-line bg-white px-3.5 text-[0.74rem] font-bold text-ink no-underline',
    'hover:border-brand-primary hover:text-brand-primary', focus,
  ),
  status: 'inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-[0.68rem] font-extrabold whitespace-nowrap',
  statusDot: 'size-1.5 rounded-full bg-current',
  dday: 'inline-flex rounded-md px-1.5 py-0.5 text-[0.7rem] font-bold tabular-nums whitespace-nowrap',
  ddayCalm: 'bg-surface-muted text-ink-muted',
  ddaySoon: 'bg-warning-soft text-warning',
  ddayToday: 'bg-danger-soft text-danger',
  // 달력 위 한 줄: 왼쪽 [‹][연 · 월][›][오늘], 오른쪽 범례.
  toolbar: 'flex flex-wrap items-center justify-between gap-x-5 gap-y-3',
  navigation: 'flex min-w-0 flex-wrap items-center gap-2',
  arrowGroup: 'inline-flex shrink-0 overflow-hidden rounded-[0.6rem] border border-line',
  arrow: classes(
    'grid size-9 cursor-pointer place-items-center border-r border-line bg-white text-ink-muted last:border-r-0',
    'hover:bg-brand-soft hover:text-brand-primary disabled:cursor-not-allowed disabled:bg-[#f6f7f8] disabled:text-[#b0b5b9]',
    focus, 'focus-visible:-outline-offset-2',
  ),
  monthSelect: classes(
    'calendar-select cursor-pointer rounded-[0.6rem] border border-transparent bg-white py-2 pr-1 text-base font-bold text-ink hover:border-line', focus,
  ),
  legend: 'flex flex-wrap items-center gap-x-3 gap-y-1 text-[0.72rem] text-ink-muted',
  legendItem: 'inline-flex items-center gap-1.5',
  legendSwatch: 'size-2.5 rounded-sm',
  note: 'text-[0.78rem] text-ink-muted',
  calendarFrame: classes(
    'overflow-x-auto rounded-[1.4rem] border border-line bg-white',
    'shadow-[0_8px_24px_rgb(32_33_36_/_4%)]',
  ),
  calendarTable: 'w-full min-w-[760px] table-fixed border-separate border-spacing-0',
  weekday: 'border-b border-line bg-[#f6f7f8] px-3 py-[0.6rem] text-left text-[0.7rem] font-bold',
  cell: 'h-[120px] max-w-0 overflow-hidden border-r border-b border-line px-1.5 py-2 align-top last:border-r-0 [tr:last-child_&]:border-b-0',
  date: 'mb-2 ml-2 inline-flex size-6 items-center justify-center rounded-full text-xs',
  events: 'm-0 flex min-w-0 max-w-full list-none flex-col gap-1 overflow-hidden p-0',
  event: 'flex w-full min-w-0 max-w-full items-center gap-1 overflow-hidden rounded-md px-1.5 py-1 text-[11px] leading-4',
  eventStart: 'bg-brand-soft text-[#175d3a]',
  eventEnd: 'bg-surface-muted text-ink-muted',
  eventSoon: 'bg-warning-soft text-warning',
  eventToday: 'bg-danger-soft text-danger',
  eventBadge: 'shrink-0 font-bold',
  eventTitle: 'block min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap font-medium',
  overflowCount: `block w-full max-w-full cursor-pointer overflow-hidden text-ellipsis whitespace-nowrap rounded px-1.5 py-0.5 text-left text-[11px] font-semibold text-brand-primary hover:bg-brand-soft hover:underline ${focus}`,
  dialogBackdrop: 'fixed inset-0 z-50 grid place-items-center bg-black/30 p-4',
  dialog: 'flex max-h-[min(680px,calc(100vh-2rem))] w-full max-w-2xl flex-col overflow-hidden rounded-[1.4rem] border border-line bg-white shadow-2xl',
  dialogHeader: 'flex shrink-0 items-start justify-between gap-4 border-b border-line px-6 py-5',
  dialogClose: `grid size-10 shrink-0 cursor-pointer place-items-center rounded-full text-2xl leading-none text-ink-muted hover:bg-surface-muted hover:text-ink ${focus}`,
  dialogEvents: 'm-0 grid list-none gap-2 p-5 pb-3',
  dialogEvent: 'flex min-w-0 items-start gap-2 rounded-xl border border-line bg-white px-3 py-3 leading-relaxed',
  dialogPagination: 'shrink-0 px-5 pb-4',
  cardTitleLink: 'text-ink no-underline hover:text-brand-primary',
  pagination: 'flex flex-wrap items-center justify-center gap-2 pt-2',
  compactPagination: 'mt-auto flex flex-wrap items-center justify-center gap-1 pt-2',
  pageButton: classes(
    'inline-flex min-h-9 min-w-9 cursor-pointer items-center justify-center rounded-full border px-3 text-[0.74rem] font-bold',
    'disabled:cursor-not-allowed disabled:opacity-40', focus,
  ),
  compactPageButton: classes(
    'inline-flex size-6 cursor-pointer items-center justify-center rounded-full border p-0 text-[0.64rem] font-bold',
    'disabled:cursor-not-allowed disabled:opacity-40', focus,
  ),
  inactivePageButton: 'border-line bg-white text-ink-muted hover:border-brand-primary hover:text-brand-primary',
  activePageButton: 'border-brand-primary bg-brand-primary text-white',
  // 진행 관리: 5열 보드(관심 · 준비 중 · 지원 완료 · 심사 중 · 결과). 열 배경은 한 가지, 설명 문장은 없습니다.
  // 보드: PC 5열. 태블릿은 열 최소 220px로 가로 스크롤, 좁은 폭(760px 미만)은 한 열 86% 폭에 스냅해 옆 열이 살짝 보입니다.
  pipelineSection: 'flex min-w-0 flex-col gap-4',
  pipelineBoard: 'grid grid-cols-[repeat(5,minmax(220px,1fr))] items-stretch gap-3 overflow-x-auto pb-2 max-chat:flex max-chat:snap-x max-chat:snap-mandatory max-chat:gap-3 max-chat:[scrollbar-width:none]',
  pipelineColumn: 'flex min-h-[360px] min-w-0 flex-col rounded-[1rem] border border-line bg-[#f6f7f8] p-2.5 max-chat:w-[86%] max-chat:shrink-0 max-chat:snap-start',
  pipelineColumnHeader: 'mb-2 flex items-center justify-between gap-2 px-1',
  pipelineColumnTitle: 'm-0 text-[0.88rem] font-extrabold tracking-[-0.02em] text-ink',
  pipelineCount: 'inline-flex size-6 shrink-0 items-center justify-center rounded-full bg-white text-[0.7rem] font-extrabold text-brand-primary shadow-sm',
  pipelineCards: 'flex flex-col gap-2 pb-2',
  pipelineEmpty: 'm-0 rounded-xl border border-dashed border-line bg-white/70 px-3 py-5 text-center text-[0.72rem] leading-[1.5] text-ink-muted',
  pipelineColumnMore: `mt-auto w-full cursor-pointer rounded-lg border border-line bg-white px-2 py-2 text-[0.72rem] font-bold text-brand-primary hover:border-brand-primary ${focus}`,
  pipelineCard: 'flex min-w-0 flex-col gap-1.5 rounded-xl border border-line bg-white p-3 shadow-[0_5px_14px_rgb(32_33_36_/_5%)]',
  pipelineCardTop: 'flex min-w-0 flex-wrap items-center gap-1.5',
  pipelineCardTitle: 'm-0 line-clamp-2 text-[0.8rem] font-bold leading-[1.4] tracking-[-0.02em] text-ink [overflow-wrap:anywhere]',
  pipelineMeta: 'm-0 truncate text-[0.7rem] leading-[1.4] text-ink-muted',
  pipelineFoot: 'mt-1 flex items-center justify-between gap-2',
  pipelineFootDate: 'text-[0.68rem] font-semibold text-ink-muted tabular-nums',
  pipelineCardAction: 'min-h-8 whitespace-nowrap px-2.5 py-1.5 text-[0.68rem]',
  pipelineError: 'flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#edc4ca] bg-[#fff5f6] px-4 py-3 text-[0.76rem] font-semibold text-danger',
  pipelineMore: 'flex flex-col items-center gap-1.5 pt-1',
  pipelineDialog: 'flex max-h-[min(720px,calc(100vh-2rem))] w-full max-w-4xl flex-col overflow-hidden rounded-[1.4rem] border border-line bg-white shadow-2xl',
  pipelineDialogCards: 'grid grid-cols-2 gap-3 p-5 pb-3 max-chat:grid-cols-1',
  skeletonRow: 'flex items-center gap-3 border-t border-line px-4 py-3',
  skeletonBar: 'h-3.5 rounded-md bg-surface-muted motion-safe:animate-pulse',
  emptyCard: 'flex flex-col items-start gap-3 rounded-[1.4rem] border border-line bg-white p-6',
} as const
