package ai.govbiz.core.partner.repository.mapper

import java.time.LocalDate
import java.time.LocalDateTime

/** MyBatis가 partner_proposal 한 행을 쓰고, 모집글·양쪽 계정·기업·공고를 조인해 읽는 데 사용하는 DB 행 값입니다. */
data class PartnerProposalDbRow(
    var id: Long = 0L,
    var recruitmentId: Long = 0L,
    var proposerAccountId: Long = 0L,
    var proposerCompanyId: Long = 0L,
    var message: String = "",
    var shareProfile: Boolean = false,
    var decision: String? = null,
    var respondedAt: LocalDateTime? = null,
    var withdrawnAt: LocalDateTime? = null,
    var createdAt: LocalDateTime? = null,
    var updatedAt: LocalDateTime? = null,
    var recruitmentTitle: String = "",
    var recruitmentDeadline: LocalDate? = null,
    var recruitmentClosedAt: LocalDateTime? = null,
    var programId: Long = 0L,
    var programSourceCode: String = "",
    var programSourceProgramId: String = "",
    var programTitle: String = "",
    var programOrganization: String = "",
    var programSummary: String = "",
    var programTargetDescription: String = "",
    var programApplicationPeriodRaw: String = "",
    var programApplicationStartDate: LocalDate? = null,
    var programApplicationEndDate: LocalDate? = null,
    var programSourceUrl: String = "",
    var proposerEmail: String = "",
    var proposerEmailVerifiedAt: LocalDateTime? = null,
    var proposerCompanyName: String = "",
    var proposerBusinessNumber: String = "",
    var proposerRegion: String = "",
    var proposerIndustry: String = "",
    var proposerFoundedYear: Int = 0,
    var proposerHomepageUrl: String? = null,
    var proposerDeletedAt: LocalDateTime? = null,
    var ownerAccountId: Long = 0L,
    var ownerEmail: String = "",
    var ownerEmailVerifiedAt: LocalDateTime? = null,
    var ownerCompanyName: String = "",
    var ownerBusinessNumber: String = "",
    var ownerRegion: String = "",
    var ownerIndustry: String = "",
    var ownerFoundedYear: Int = 0,
    var ownerHomepageUrl: String? = null,
    var ownerDeletedAt: LocalDateTime? = null,
)
